const phrases = [

// AIRPORT

{m:"airport",en:"Where is the airport?",pron:"uer iz dhi erport",pt:"Onde fica o aeroporto"},
{m:"airport",en:"Where is my gate?",pron:"uer iz mai gueit",pt:"Onde é meu portão"},
{m:"airport",en:"Where is baggage claim?",pron:"uer iz baguej cleim",pt:"Onde retiro minha bagagem"},
{m:"airport",en:"Where is immigration?",pron:"uer iz imigreixon",pt:"Onde fica a imigração"},
{m:"airport",en:"Where is customs?",pron:"uer iz câstoms",pt:"Onde é a alfândega"},
{m:"airport",en:"Where is the restroom?",pron:"uer iz dhi réstrum",pt:"Onde é o banheiro"},
{m:"airport",en:"Where is the exit?",pron:"uer iz dhi eksit",pt:"Onde é a saída"},
{m:"airport",en:"Where is security?",pron:"uer iz sicuriti",pt:"Onde é a segurança"},
{m:"airport",en:"Where is check in?",pron:"uer iz tchek in",pt:"Onde faço check in"},
{m:"airport",en:"Where is boarding?",pron:"uer iz bording",pt:"Onde é o embarque"},

{m:"airport",en:"Which terminal?",pron:"uich terminal",pt:"Qual terminal"},
{m:"airport",en:"Which gate?",pron:"uich gueit",pt:"Qual portão"},
{m:"airport",en:"What time is boarding?",pron:"uat taim iz bording",pt:"Que horas é o embarque"},
{m:"airport",en:"What time is the flight?",pron:"uat taim iz dhi flait",pt:"Que horas é o voo"},
{m:"airport",en:"Is the flight on time?",pron:"iz dhi flait on taim",pt:"O voo está no horário"},
{m:"airport",en:"Is the flight delayed?",pron:"iz dhi flait dileid",pt:"O voo está atrasado"},
{m:"airport",en:"Is the flight canceled?",pron:"iz dhi flait cênseld",pt:"O voo foi cancelado"},
{m:"airport",en:"My flight is delayed.",pron:"mai flait iz dileid",pt:"Meu voo está atrasado"},
{m:"airport",en:"My flight was canceled.",pron:"mai flait uaz cênseld",pt:"Meu voo foi cancelado"},
{m:"airport",en:"I missed my flight.",pron:"ai mist mai flait",pt:"Perdi meu voo"},

{m:"airport",en:"I lost my luggage.",pron:"ai lost mai laguedj",pt:"Perdi minha bagagem"},
{m:"airport",en:"My bag is missing.",pron:"mai bag iz mísing",pt:"Minha mala sumiu"},
{m:"airport",en:"I only have carry on.",pron:"ai onli rév cari on",pt:"Só tenho bagagem de mão"},
{m:"airport",en:"I have two bags.",pron:"ai rév tu bags",pt:"Tenho duas malas"},
{m:"airport",en:"Can you help me?",pron:"ken iu rélp mi",pt:"Pode me ajudar"},
{m:"airport",en:"I need help.",pron:"ai nid rélp",pt:"Preciso de ajuda"},
{m:"airport",en:"I don't understand.",pron:"ai dont anderstend",pt:"Não entendo"},
{m:"airport",en:"Please speak slowly.",pron:"pliz spik slouli",pt:"Fale devagar por favor"},
{m:"airport",en:"Can you repeat?",pron:"ken iu ripit",pt:"Pode repetir"},
{m:"airport",en:"Where is the information desk?",pron:"uer iz dhi informêixon desk",pt:"Onde é o balcão de informação"},

{m:"airport",en:"Where can I get a taxi?",pron:"uer ken ai guet a taxi",pt:"Onde pego um taxi"},
{m:"airport",en:"Where is the taxi line?",pron:"uer iz dhi taxi lain",pt:"Onde é a fila de taxi"},
{m:"airport",en:"Where is Uber pickup?",pron:"uer iz uber picap",pt:"Onde pega Uber"},
{m:"airport",en:"Where is the shuttle?",pron:"uer iz dhi xatel",pt:"Onde é o transfer"},
{m:"airport",en:"Where is the train?",pron:"uer iz dhi trein",pt:"Onde é o trem"},
{m:"airport",en:"Where is the bus?",pron:"uer iz dhi bus",pt:"Onde é o ônibus"},
{m:"airport",en:"Where can I buy tickets?",pron:"uer ken ai bai tikets",pt:"Onde compro passagens"},
{m:"airport",en:"Where is the ATM?",pron:"uer iz dhi ei ti em",pt:"Onde é o caixa eletrônico"},
{m:"airport",en:"Where can I exchange money?",pron:"uer ken ai exchêinj mani",pt:"Onde troco dinheiro"},
{m:"airport",en:"Where is the currency exchange?",pron:"uer iz dhi cârenci exchêinj",pt:"Onde é o câmbio"},

{m:"airport",en:"Can I charge my phone?",pron:"ken ai tcharj mai foun",pt:"Posso carregar meu celular"},
{m:"airport",en:"Where is a charger?",pron:"uer iz a tcharjer",pt:"Onde tem carregador"},
{m:"airport",en:"Where is free wifi?",pron:"uer iz fri uaifai",pt:"Onde tem wifi grátis"},
{m:"airport",en:"What is the wifi password?",pron:"uat iz dhi uaifai pasuord",pt:"Qual a senha do wifi"},
{m:"airport",en:"Can I sit here?",pron:"ken ai sit rir",pt:"Posso sentar aqui"},
{m:"airport",en:"Is this seat taken?",pron:"iz dis sit teiken",pt:"Esse assento está ocupado"},
{m:"airport",en:"This seat is free.",pron:"dis sit iz fri",pt:"Esse assento está livre"},
{m:"airport",en:"Excuse me.",pron:"excuse mi",pt:"Com licença"},
{m:"airport",en:"Thank you.",pron:"thenk iu",pt:"Obrigado"},
{m:"airport",en:"Thank you very much.",pron:"thenk iu veri match",pt:"Muito obrigado"},

{m:"airport",en:"Have a good flight.",pron:"rév a gud flait",pt:"Tenha um bom voo"},
{m:"airport",en:"Safe travels.",pron:"seif travels",pt:"Boa viagem"},
{m:"airport",en:"See you soon.",pron:"si iu sun",pt:"Até breve"},
{m:"airport",en:"Goodbye.",pron:"gud bai",pt:"Tchau"}
{m:"airport",en:"My gate changed.",pron:"mai gueit tcheindj",pt:"Meu portão mudou."},
{m:"airport",en:"Where is boarding?",pron:"uer iz bording",pt:"Onde é o embarque?"},
{m:"airport",en:"Is this the boarding line?",pron:"iz dis de bording lain",pt:"Essa é a fila de embarque?"},
{m:"airport",en:"Can I board now?",pron:"ken ai bord nau",pt:"Posso embarcar agora?"},
{m:"airport",en:"Where is the terminal?",pron:"uer iz de terminal",pt:"Onde é o terminal?"},
{m:"airport",en:"Is this terminal A?",pron:"iz dis terminal ei",pt:"Esse é o terminal A?"},
{m:"airport",en:"Where can I get water?",pron:"uer ken ai get uóter",pt:"Onde posso pegar água?"},
{m:"airport",en:"Where can I buy food?",pron:"uer ken ai bai fud",pt:"Onde posso comprar comida?"},
{m:"airport",en:"Where is the lounge?",pron:"uer iz de launj",pt:"Onde é o lounge?"},
{m:"airport",en:"Can I sit here?",pron:"ken ai sit rir",pt:"Posso sentar aqui?"},
  
// HOTEL

{m:"hotel",en:"I have a reservation.",pron:"ai rév a rezervêixon",pt:"Eu tenho uma reserva"},
{m:"hotel",en:"I need a room.",pron:"ai nid a rum",pt:"Preciso de um quarto"},
{m:"hotel",en:"Do you have rooms?",pron:"du iu rév rums",pt:"Vocês tem quartos"},
{m:"hotel",en:"Is there a vacancy?",pron:"iz der a veicânci",pt:"Tem vaga"},
{m:"hotel",en:"One night please.",pron:"uan nait pliz",pt:"Uma noite por favor"},
{m:"hotel",en:"Two nights please.",pron:"tu naits pliz",pt:"Duas noites por favor"},
{m:"hotel",en:"What is the price?",pron:"uat iz dhi prais",pt:"Qual o preço"},
{m:"hotel",en:"Is breakfast included?",pron:"iz brekfast inclúded",pt:"Café da manhã está incluso"},
{m:"hotel",en:"Is wifi included?",pron:"iz uaifai inclúded",pt:"Wifi está incluso"},
{m:"hotel",en:"What time is check in?",pron:"uat taim iz tchek in",pt:"Que horas é o check in"},

{m:"hotel",en:"What time is checkout?",pron:"uat taim iz tchek aut",pt:"Que horas é o checkout"},
{m:"hotel",en:"Can I check in early?",pron:"ken ai tchek in erli",pt:"Posso entrar mais cedo"},
{m:"hotel",en:"Can I check out late?",pron:"ken ai tchek aut leit",pt:"Posso sair mais tarde"},
{m:"hotel",en:"Where is my room?",pron:"uer iz mai rum",pt:"Onde é meu quarto"},
{m:"hotel",en:"What floor?",pron:"uat flor",pt:"Qual andar"},
{m:"hotel",en:"Where is the elevator?",pron:"uer iz dhi elevêitor",pt:"Onde é o elevador"},
{m:"hotel",en:"Where is the lobby?",pron:"uer iz dhi lobi",pt:"Onde é o lobby"},
{m:"hotel",en:"Where is the restaurant?",pron:"uer iz dhi réstaurant",pt:"Onde é o restaurante"},
{m:"hotel",en:"Where is the pool?",pron:"uer iz dhi pul",pt:"Onde é a piscina"},
{m:"hotel",en:"Where is the gym?",pron:"uer iz dhi jim",pt:"Onde é a academia"},

{m:"hotel",en:"Do you have wifi?",pron:"du iu rév uaifai",pt:"Vocês tem wifi"},
{m:"hotel",en:"What is the wifi password?",pron:"uat iz dhi uaifai pasuord",pt:"Qual a senha do wifi"},
{m:"hotel",en:"Can you call a taxi?",pron:"ken iu col a taxi",pt:"Pode chamar um taxi"},
{m:"hotel",en:"Can you wake me up?",pron:"ken iu ueik mi ap",pt:"Pode me acordar"},
{m:"hotel",en:"I need towels.",pron:"ai nid tauels",pt:"Preciso de toalhas"},
{m:"hotel",en:"I need soap.",pron:"ai nid soup",pt:"Preciso de sabonete"},
{m:"hotel",en:"I need toilet paper.",pron:"ai nid toilet peiper",pt:"Preciso de papel higiênico"},
{m:"hotel",en:"The room is cold.",pron:"dhi rum iz cold",pt:"O quarto está frio"},
{m:"hotel",en:"The room is hot.",pron:"dhi rum iz rot",pt:"O quarto está quente"},
{m:"hotel",en:"The shower is not working.",pron:"dhi xauer iz not uorking",pt:"O chuveiro não funciona"},

{m:"hotel",en:"The air conditioner is broken.",pron:"dhi er condicioner iz broken",pt:"O ar condicionado está quebrado"},
{m:"hotel",en:"The TV is not working.",pron:"dhi ti vi iz not uorking",pt:"A TV não funciona"},
{m:"hotel",en:"Can I change rooms?",pron:"ken ai tcheinj rums",pt:"Posso trocar de quarto"},
{m:"hotel",en:"Can I get another room?",pron:"ken ai guet anader rum",pt:"Posso pegar outro quarto"},
{m:"hotel",en:"Can I leave my luggage?",pron:"ken ai liv mai laguedj",pt:"Posso deixar minha bagagem"},
{m:"hotel",en:"Can you store my bags?",pron:"ken iu stor mai bags",pt:"Pode guardar minhas malas"},
{m:"hotel",en:"I will come back later.",pron:"ai uil cam bak later",pt:"Volto depois"},
{m:"hotel",en:"I am checking out.",pron:"ai am tcheking aut",pt:"Estou fazendo checkout"},
{m:"hotel",en:"Can I pay now?",pron:"ken ai pei nau",pt:"Posso pagar agora"},
{m:"hotel",en:"Can I pay with card?",pron:"ken ai pei uith card",pt:"Posso pagar com cartão"},

{m:"hotel",en:"Can I pay cash?",pron:"ken ai pei kash",pt:"Posso pagar em dinheiro"},
{m:"hotel",en:"Do you accept credit cards?",pron:"du iu accept crédit cards",pt:"Aceitam cartão de crédito"},
{m:"hotel",en:"Can I get a receipt?",pron:"ken ai guet a risit",pt:"Posso pegar o recibo"},
{m:"hotel",en:"Everything is fine.",pron:"evriting iz fain",pt:"Está tudo bem"},
{m:"hotel",en:"The room is perfect.",pron:"dhi rum iz perfect",pt:"O quarto está perfeito"},
{m:"hotel",en:"Thank you.",pron:"thenk iu",pt:"Obrigado"},
{m:"hotel",en:"Thank you very much.",pron:"thenk iu veri match",pt:"Muito obrigado"},
{m:"hotel",en:"Have a good day.",pron:"rév a gud dei",pt:"Tenha um bom dia"},
{m:"hotel",en:"See you tomorrow.",pron:"si iu tumoro",pt:"Até amanhã"},
{m:"hotel",en:"Goodbye.",pron:"gud bai",pt:"Tchau"
{m:"hotel",en:"Do you have room service?",pron:"du iu rév rum sârviss",pt:"Vocês têm serviço de quarto?"},
{m:"hotel",en:"Can I get more towels?",pron:"ken ai get mor tauels",pt:"Pode trazer mais toalhas?"},
{m:"hotel",en:"Can I get water?",pron:"ken ai get uóter",pt:"Pode trazer água?"},
{m:"hotel",en:"The room is cold.",pron:"de rum iz cold",pt:"O quarto está frio."},
{m:"hotel",en:"The room is hot.",pron:"de rum iz hot",pt:"O quarto está quente."},
{m:"hotel",en:"The shower is broken.",pron:"de xauer iz broken",pt:"O chuveiro está quebrado."},
{m:"hotel",en:"The TV is not working.",pron:"de ti vi iz not uorking",pt:"A TV não funciona."},
{m:"hotel",en:"Can someone help me?",pron:"ken samuan relp mi",pt:"Alguém pode me ajudar?"},
{m:"hotel",en:"I forgot my key.",pron:"ai forgot mai ki",pt:"Esqueci minha chave."},
{m:"hotel",en:"I need a new key.",pron:"ai nid a nu ki",pt:"Preciso de uma nova chave."},
 
// RESTAURANT

{m:"restaurant",en:"Can I see the menu?",pron:"ken ai sii de ménu",pt:"Posso ver o cardápio"},
{m:"restaurant",en:"Do you have an English menu?",pron:"du iu rév an inglish ménu",pt:"Tem cardápio em inglês"},
{m:"restaurant",en:"What do you recommend?",pron:"uat du iu recoménd",pt:"O que você recomenda"},
{m:"restaurant",en:"I want this.",pron:"ai uant dis",pt:"Eu quero isso"},
{m:"restaurant",en:"I will have this.",pron:"ai uil rév dis",pt:"Vou querer isso"},
{m:"restaurant",en:"Water please.",pron:"uóter pliz",pt:"Água por favor"},
{m:"restaurant",en:"No ice please.",pron:"no ais pliz",pt:"Sem gelo por favor"},
{m:"restaurant",en:"Another water please.",pron:"anader uóter pliz",pt:"Outra água por favor"},
{m:"restaurant",en:"One beer please.",pron:"uan bir pliz",pt:"Uma cerveja por favor"},
{m:"restaurant",en:"Two beers please.",pron:"tu biers pliz",pt:"Duas cervejas por favor"},

{m:"restaurant",en:"A coffee please.",pron:"a cófi pliz",pt:"Um café por favor"},
{m:"restaurant",en:"Do you have wine?",pron:"du iu rév uain",pt:"Vocês tem vinho"},
{m:"restaurant",en:"Do you have beer?",pron:"du iu rév bir",pt:"Vocês tem cerveja"},
{m:"restaurant",en:"Do you have dessert?",pron:"du iu rév dizért",pt:"Tem sobremesa"},
{m:"restaurant",en:"Is this spicy?",pron:"iz dis spaisi",pt:"Isso é apimentado"},
{m:"restaurant",en:"Not spicy please.",pron:"not spaisi pliz",pt:"Sem pimenta por favor"},
{m:"restaurant",en:"Is this good?",pron:"iz dis gud",pt:"Isso é bom"},
{m:"restaurant",en:"This is delicious.",pron:"dis iz delíshus",pt:"Isso está delicioso"},
{m:"restaurant",en:"This is very good.",pron:"dis iz veri gud",pt:"Isso está muito bom"},
{m:"restaurant",en:"The food is amazing.",pron:"de fud iz amêizing",pt:"A comida é incrível"},

{m:"restaurant",en:"Can I get the check?",pron:"ken ai guet de chek",pt:"Pode trazer a conta"},
{m:"restaurant",en:"The check please.",pron:"de chek pliz",pt:"A conta por favor"},
{m:"restaurant",en:"Can we split the check?",pron:"ken ui split de chek",pt:"Podemos dividir a conta"},
{m:"restaurant",en:"Separate checks please.",pron:"séperet cheks pliz",pt:"Contas separadas por favor"},
{m:"restaurant",en:"Can I pay now?",pron:"ken ai pei nau",pt:"Posso pagar agora"},
{m:"restaurant",en:"Can I pay with card?",pron:"ken ai pei uith card",pt:"Posso pagar com cartão"},
{m:"restaurant",en:"Can I pay cash?",pron:"ken ai pei kash",pt:"Posso pagar em dinheiro"},
{m:"restaurant",en:"Do you accept credit cards?",pron:"du iu accept crédit cards",pt:"Aceitam cartão de crédito"},
{m:"restaurant",en:"Is tip included?",pron:"iz tip inclúded",pt:"A gorjeta está incluída"},
{m:"restaurant",en:"Keep the change.",pron:"kip de tcheinj",pt:"Fique com o troco"},

{m:"restaurant",en:"A table for two.",pron:"a teibol for tu",pt:"Mesa para dois"},
{m:"restaurant",en:"A table for three.",pron:"a teibol for tri",pt:"Mesa para três"},
{m:"restaurant",en:"Is there a table?",pron:"iz der a teibol",pt:"Tem mesa"},
{m:"restaurant",en:"How long is the wait?",pron:"rau long iz de ueit",pt:"Quanto tempo de espera"},
{m:"restaurant",en:"Can we sit here?",pron:"ken ui sit rir",pt:"Podemos sentar aqui"},
{m:"restaurant",en:"Can we sit outside?",pron:"ken ui sit autsaide",pt:"Podemos sentar fora"},
{m:"restaurant",en:"Can we sit inside?",pron:"ken ui sit inside",pt:"Podemos sentar dentro"},
{m:"restaurant",en:"I am ready to order.",pron:"ai am rédi tu órder",pt:"Estou pronto para pedir"},
{m:"restaurant",en:"We are ready to order.",pron:"ui ar rédi tu órder",pt:"Estamos prontos para pedir"},
{m:"restaurant",en:"Just a minute.",pron:"djast a mínit",pt:"Só um minuto"},

{m:"restaurant",en:"Give me a minute.",pron:"guiv mi a mínit",pt:"Me dê um minuto"},
{m:"restaurant",en:"I need more time.",pron:"ai nid mor taim",pt:"Preciso de mais tempo"},
{m:"restaurant",en:"Excuse me.",pron:"excuse mi",pt:"Com licença"},
{m:"restaurant",en:"Sorry.",pron:"sóri",pt:"Desculpa"},
{m:"restaurant",en:"Thank you.",pron:"thenk iu",pt:"Obrigado"},
{m:"restaurant",en:"Thank you very much.",pron:"thenk iu veri match",pt:"Muito obrigado"},
{m:"restaurant",en:"Everything is great.",pron:"evriting iz greit",pt:"Está tudo ótimo"},
{m:"restaurant",en:"The service is great.",pron:"de sârviss iz greit",pt:"O serviço está ótimo"},
{m:"restaurant",en:"We loved the food.",pron:"ui lavd de fud",pt:"Nós adoramos a comida"},
{m:"restaurant",en:"See you next time.",pron:"si iu nekst taim",pt:"Até a próxima"}
{m:"restaurant",en:"Is this fresh?",pron:"iz dis fresh",pt:"Isso é fresco?"},
{m:"restaurant",en:"Is this hot?",pron:"iz dis hot",pt:"Isso está quente?"},
{m:"restaurant",en:"Is this cold?",pron:"iz dis cold",pt:"Isso está frio?"},
{m:"restaurant",en:"More napkins please.",pron:"mor napkins pliz",pt:"Mais guardanapos por favor."},
{m:"restaurant",en:"Can I get more bread?",pron:"ken ai get mor bred",pt:"Pode trazer mais pão?"},
{m:"restaurant",en:"This is perfect.",pron:"dis iz perfect",pt:"Isso está perfeito."},
{m:"restaurant",en:"This is too salty.",pron:"dis iz tu solti",pt:"Isso está muito salgado."},
{m:"restaurant",en:"This is too spicy.",pron:"dis iz tu spaisi",pt:"Isso está muito apimentado."},
{m:"restaurant",en:"Can I get another drink?",pron:"ken ai get anader drink",pt:"Pode trazer outra bebida?"},
{m:"restaurant",en:"The food is great.",pron:"de fud iz greit",pt:"A comida está ótima."},
 
// TRANSPORT

{m:"transport",en:"Where is the subway?",pron:"uer iz dhi sâbuei",pt:"Onde fica o metrô"},
{m:"transport",en:"Where is the bus stop?",pron:"uer iz dhi bus stop",pt:"Onde é o ponto de ônibus"},
{m:"transport",en:"Where is the train station?",pron:"uer iz dhi trein steixon",pt:"Onde é a estação de trem"},
{m:"transport",en:"Where is the taxi?",pron:"uer iz dhi taxi",pt:"Onde pego taxi"},
{m:"transport",en:"Where can I get a taxi?",pron:"uer ken ai guet a taxi",pt:"Onde pego um taxi"},
{m:"transport",en:"Call a taxi please.",pron:"col a taxi pliz",pt:"Chame um taxi por favor"},
{m:"transport",en:"I need a taxi.",pron:"ai nid a taxi",pt:"Preciso de um taxi"},
{m:"transport",en:"I need an Uber.",pron:"ai nid an uber",pt:"Preciso de um Uber"},
{m:"transport",en:"Take me downtown.",pron:"teik mi daun taun",pt:"Me leve ao centro"},
{m:"transport",en:"Take me to the airport.",pron:"teik mi tu dhi erport",pt:"Me leve ao aeroporto"},

{m:"transport",en:"Stop here please.",pron:"stop rir pliz",pt:"Pare aqui por favor"},
{m:"transport",en:"Stop there please.",pron:"stop der pliz",pt:"Pare ali por favor"},
{m:"transport",en:"How much is the ticket?",pron:"rau match iz dhi tiket",pt:"Quanto custa a passagem"},
{m:"transport",en:"How much is the fare?",pron:"rau match iz dhi fér",pt:"Quanto custa a corrida"},
{m:"transport",en:"How long does it take?",pron:"rau long daz it teik",pt:"Quanto tempo demora"},
{m:"transport",en:"Is it far?",pron:"iz it far",pt:"É longe"},
{m:"transport",en:"Is it near?",pron:"iz it nir",pt:"É perto"},
{m:"transport",en:"Turn left.",pron:"tern left",pt:"Vire à esquerda"},
{m:"transport",en:"Turn right.",pron:"tern rait",pt:"Vire à direita"},
{m:"transport",en:"Go straight.",pron:"gou streit",pt:"Siga em frente"},
{m:"transport",en:"Slow down please.",pron:"slou daun pliz",pt:"Devagar por favor"},
{m:"transport",en:"Stop the car.",pron:"stop dhi car",pt:"Pare o carro"},
{m:"transport",en:"Wait here please.",pron:"ueit rir pliz",pt:"Espere aqui por favor"},
{m:"transport",en:"Can you wait?",pron:"ken iu ueit",pt:"Pode esperar"},
{m:"transport",en:"Just a minute.",pron:"djast a mínit",pt:"Só um minuto"},
{m:"transport",en:"I will be quick.",pron:"ai uil bi kuik",pt:"Serei rápido"},
{m:"transport",en:"Thank you driver.",pron:"thenk iu draiver",pt:"Obrigado motorista"},
{m:"transport",en:"Keep the change.",pron:"kip dhi tcheinj",pt:"Fique com o troco"},
{m:"transport",en:"Can I pay with card?",pron:"ken ai pei uith card",pt:"Posso pagar com cartão"},
{m:"transport",en:"Can I pay cash?",pron:"ken ai pei kash",pt:"Posso pagar em dinheiro"}
{m:"transport",en:"Is tip included?",pron:"iz tip inclúded",pt:"A gorjeta está incluída"},
{m:"transport",en:"Do I need to tip?",pron:"du ai nid tu tip",pt:"Preciso dar gorjeta"},
{m:"transport",en:"How much tip?",pron:"rau match tip",pt:"Quanto de gorjeta"},
{m:"transport",en:"Keep the change.",pron:"kip de tcheinj",pt:"Fique com o troco"},
{m:"transport",en:"Thank you driver.",pron:"thenk iu draiver",pt:"Obrigado motorista"},
{m:"transport",en:"The service was great.",pron:"de sârviss uaz greit",pt:"O serviço foi ótimo"
{m:"transport",en:"Where is the metro?",pron:"uer iz de metro",pt:"Onde fica o metrô?"},
{m:"transport",en:"Which line?",pron:"uich lain",pt:"Qual linha?"},
{m:"transport",en:"Which platform?",pron:"uich platform",pt:"Qual plataforma?"},
{m:"transport",en:"Does this bus stop here?",pron:"daz dis bus stop rir",pt:"Esse ônibus para aqui?"},
{m:"transport",en:"Is this the right bus?",pron:"iz dis de rait bus",pt:"Esse é o ônibus certo?"},
{m:"transport",en:"When is the next bus?",pron:"uen iz de nekst bus",pt:"Quando é o próximo ônibus?"},
{m:"transport",en:"When is the next train?",pron:"uen iz de nekst trein",pt:"Quando é o próximo trem?"},
{m:"transport",en:"Do I need a ticket?",pron:"du ai nid a tiket",pt:"Preciso de passagem?"},
{m:"transport",en:"Where can I buy a ticket?",pron:"uer ken ai bai a tiket",pt:"Onde compro passagem?"},
{m:"transport",en:"Can I pay here?",pron:"ken ai pei rir",pt:"Posso pagar aqui?"},

 
// SHOPPING

{m:"shopping",en:"How much is this?",pron:"rau match iz dis",pt:"Quanto custa isso?"},
{m:"shopping",en:"How much is that?",pron:"rau match iz det",pt:"Quanto custa aquilo?"},
{m:"shopping",en:"Is this on sale?",pron:"iz dis on seil",pt:"Isso está em promoção?"},
{m:"shopping",en:"Do you have a discount?",pron:"du iu rév a diskaunt",pt:"Tem desconto?"},
{m:"shopping",en:"Can you give a discount?",pron:"ken iu guiv a diskaunt",pt:"Pode dar desconto?"},
{m:"shopping",en:"Do you have this in black?",pron:"du iu rév dis in blak",pt:"Tem isso em preto?"},
{m:"shopping",en:"Do you have this in blue?",pron:"du iu rév dis in blu",pt:"Tem isso em azul?"},
{m:"shopping",en:"Do you have a bigger size?",pron:"du iu rév a biger saiz",pt:"Tem tamanho maior?"},
{m:"shopping",en:"Do you have a smaller size?",pron:"du iu rév a smoler saiz",pt:"Tem tamanho menor?"},
{m:"shopping",en:"Can I try this on?",pron:"ken ai trai dis on",pt:"Posso experimentar isso?"},

{m:"shopping",en:"Where is the fitting room?",pron:"uer iz de fiting rum",pt:"Onde é o provador?"},
{m:"shopping",en:"I like this.",pron:"ai laik dis",pt:"Eu gostei disso."},
{m:"shopping",en:"I don't like this.",pron:"ai dont laik dis",pt:"Eu não gostei disso."},
{m:"shopping",en:"I will take this.",pron:"ai uil teik dis",pt:"Vou levar isso."},
{m:"shopping",en:"I don't need a bag.",pron:"ai dont nid a bag",pt:"Não preciso de sacola."},
{m:"shopping",en:"Can I pay with card?",pron:"ken ai pei uith card",pt:"Posso pagar com cartão?"},
{m:"shopping",en:"Can I pay cash?",pron:"ken ai pei kash",pt:"Posso pagar em dinheiro?"},
{m:"shopping",en:"Do you accept credit cards?",pron:"du iu accept credit cards",pt:"Aceitam cartão de crédito?"},
{m:"shopping",en:"Where is the cashier?",pron:"uer iz de kashier",pt:"Onde é o caixa?"},
{m:"shopping",en:"I am just looking.",pron:"ai am djust luking",pt:"Estou só olhando."}
{m:"shopping",en:"Do you have this?",pron:"du iu rév dis",pt:"Você tem isso?"},
{m:"shopping",en:"Do you sell this?",pron:"du iu sel dis",pt:"Você vende isso?"},
{m:"shopping",en:"Can I see that?",pron:"ken ai sii det",pt:"Posso ver aquilo?"},
{m:"shopping",en:"Is this good quality?",pron:"iz dis gud cuóliti",pt:"Isso é de boa qualidade?"},
{m:"shopping",en:"This is expensive.",pron:"dis iz expênsiv",pt:"Isso é caro."},
{m:"shopping",en:"This is cheap.",pron:"dis iz tchip",pt:"Isso é barato."},
{m:"shopping",en:"Can I return this?",pron:"ken ai ritârn dis",pt:"Posso devolver isso?"},
{m:"shopping",en:"Do you have another color?",pron:"du iu rév anader color",pt:"Tem outra cor?"},
{m:"shopping",en:"Where is the store?",pron:"uer iz de stor",pt:"Onde fica a loja?"},
{m:"shopping",en:"Where is the mall?",pron:"uer iz de mol",pt:"Onde fica o shopping?"},

// TOURISM

{m:"tourism",en:"Where is the beach?",pron:"uer iz de bitch",pt:"Onde fica a praia?"},
{m:"tourism",en:"Where is the museum?",pron:"uer iz de miuziam",pt:"Onde fica o museu?"},
{m:"tourism",en:"Where is downtown?",pron:"uer iz daun taun",pt:"Onde é o centro?"},
{m:"tourism",en:"Where is the park?",pron:"uer iz de park",pt:"Onde é o parque?"},
{m:"tourism",en:"Where is the restroom?",pron:"uer iz de restroom",pt:"Onde fica o banheiro?"},
{m:"tourism",en:"Where can I take pictures?",pron:"uer ken ai teik pikchers",pt:"Onde posso tirar fotos?"},
{m:"tourism",en:"Can you take a picture?",pron:"ken iu teik a pikcher",pt:"Pode tirar uma foto?"},
{m:"tourism",en:"This place is beautiful.",pron:"dis pleis iz biutiful",pt:"Esse lugar é lindo."},
{m:"tourism",en:"This is amazing.",pron:"dis iz ameizing",pt:"Isso é incrível."},
{m:"tourism",en:"I love this place.",pron:"ai lav dis pleis",pt:"Eu amo esse lugar."},

{m:"tourism",en:"Is it far from here?",pron:"iz it far from rir",pt:"É longe daqui?"},
{m:"tourism",en:"Is it near?",pron:"iz it nir",pt:"É perto?"},
{m:"tourism",en:"How do I get there?",pron:"rau du ai get der",pt:"Como chego lá?"},
{m:"tourism",en:"Can we walk there?",pron:"ken ui uok der",pt:"Podemos ir andando?"},
{m:"tourism",en:"Is it safe here?",pron:"iz it seif rir",pt:"É seguro aqui?"},
{m:"tourism",en:"Is it open today?",pron:"iz it open tudêi",pt:"Está aberto hoje?"},
{m:"tourism",en:"What time does it open?",pron:"uat taim daz it open",pt:"Que horas abre?"},
{m:"tourism",en:"What time does it close?",pron:"uat taim daz it clous",pt:"Que horas fecha?"},
{m:"tourism",en:"Where can I buy tickets?",pron:"uer ken ai bai tikets",pt:"Onde compro ingressos?"},
{m:"tourism",en:"Two tickets please.",pron:"tu tikets pliz",pt:"Dois ingressos por favor."}


// CONVERSATION

{m:"conversation",en:"Hello.",pron:"relou",pt:"Olá."},
{m:"conversation",en:"Hi.",pron:"rai",pt:"Oi."},
{m:"conversation",en:"Good morning.",pron:"gud morning",pt:"Bom dia."},
{m:"conversation",en:"Good afternoon.",pron:"gud afternun",pt:"Boa tarde."},
{m:"conversation",en:"Good evening.",pron:"gud ivning",pt:"Boa noite."},
{m:"conversation",en:"How are you?",pron:"rau ar iu",pt:"Como você está?"},
{m:"conversation",en:"I am good.",pron:"ai am gud",pt:"Estou bem."},
{m:"conversation",en:"Nice to meet you.",pron:"nais tu mit iu",pt:"Prazer em conhecer você."},
{m:"conversation",en:"Where are you from?",pron:"uer ar iu from",pt:"De onde você é?"},
{m:"conversation",en:"I am from Brazil.",pron:"ai am from brazil",pt:"Sou do Brasil."},

{m:"conversation",en:"I am on vacation.",pron:"ai am on veikeixon",pt:"Estou de férias."},
{m:"conversation",en:"This is my first time here.",pron:"dis iz mai fârst taim rir",pt:"É minha primeira vez aqui."},
{m:"conversation",en:"I love this city.",pron:"ai lav dis siti",pt:"Eu amo essa cidade."},
{m:"conversation",en:"This place is great.",pron:"dis pleis iz greit",pt:"Esse lugar é ótimo."},
{m:"conversation",en:"Thank you.",pron:"thenk iu",pt:"Obrigado."},
{m:"conversation",en:"Thank you very much.",pron:"thenk iu veri match",pt:"Muito obrigado."},
{m:"conversation",en:"You're welcome.",pron:"ior uélcom",pt:"De nada."},
{m:"conversation",en:"Excuse me.",pron:"excuse mi",pt:"Com licença."},
{m:"conversation",en:"Sorry.",pron:"sóri",pt:"Desculpa."},
{m:"conversation",en:"Goodbye.",pron:"gud bai",pt:"Tchau."}
{m:"conversation",en:"Where are you staying?",pron:"uer ar iu steiing",pt:"Onde você está hospedado?"},
{m:"conversation",en:"Do you like this city?",pron:"du iu laik dis siti",pt:"Você gosta dessa cidade?"},
{m:"conversation",en:"It is beautiful here.",pron:"it iz biutiful rir",pt:"É lindo aqui."},
{m:"conversation",en:"I am traveling.",pron:"ai am travelin",pt:"Estou viajando."},
{m:"conversation",en:"I am visiting.",pron:"ai am viziting",pt:"Estou visitando."},
{m:"conversation",en:"This is my first time.",pron:"dis iz mai fârst taim",pt:"É minha primeira vez."},
{m:"conversation",en:"I will come back.",pron:"ai uil cam bak",pt:"Vou voltar."},
{m:"conversation",en:"I like this place.",pron:"ai laik dis pleis",pt:"Eu gosto desse lugar."},
{m:"conversation",en:"Have a nice trip.",pron:"rév a nais trip",pt:"Tenha uma boa viagem."},
{m:"conversation",en:"See you later.",pron:"si iu later",pt:"Até mais."},

// EMERGENCY

{m:"emergency",en:"Help.",pron:"relp",pt:"Socorro."},
{m:"emergency",en:"Call the police.",pron:"col de polis",pt:"Chame a polícia."},
{m:"emergency",en:"Call an ambulance.",pron:"col an ambiulans",pt:"Chame uma ambulância."},
{m:"emergency",en:"I need a doctor.",pron:"ai nid a doctor",pt:"Preciso de um médico."},
{m:"emergency",en:"I need help.",pron:"ai nid relp",pt:"Preciso de ajuda."},
{m:"emergency",en:"I am lost.",pron:"ai am lost",pt:"Estou perdido."},
{m:"emergency",en:"I lost my passport.",pron:"ai lost mai passport",pt:"Perdi meu passaporte."},
{m:"emergency",en:"I lost my phone.",pron:"ai lost mai foun",pt:"Perdi meu celular."},
{m:"emergency",en:"I was robbed.",pron:"ai uaz robd",pt:"Fui roubado."},
{m:"emergency",en:"Where is the hospital?",pron:"uer iz de hospital",pt:"Onde fica o hospital?"}
{m:"emergency",en:"I need police.",pron:"ai nid polis",pt:"Preciso da polícia."},
{m:"emergency",en:"I feel sick.",pron:"ai fil sik",pt:"Estou me sentindo mal."},
{m:"emergency",en:"I need medicine.",pron:"ai nid medisin",pt:"Preciso de remédio."},
{m:"emergency",en:"Where is the pharmacy?",pron:"uer iz de farmaci",pt:"Onde fica a farmácia?"},
{m:"emergency",en:"Please help me.",pron:"pliz relp mi",pt:"Por favor me ajude."},
{m:"emergency",en:"I am hurt.",pron:"ai am rurt",pt:"Estou ferido."},
{m:"emergency",en:"Call security.",pron:"col sicuriti",pt:"Chame a segurança."},
{m:"emergency",en:"I need assistance.",pron:"ai nid assistens",pt:"Preciso de assistência."},
{m:"emergency",en:"This is urgent.",pron:"dis iz ârjent",pt:"Isso é urgente."},
{m:"emergency",en:"Please hurry.",pron:"pliz rari",pt:"Por favor rápido."}

];
