const lessons=[

// AIRPORT
{m:"airport",en:"Where is the airport?",pron:"uer iz dhi erport",pt:"Onde fica o aeroporto"},
{m:"airport",en:"Where is my gate?",pron:"uer iz mai gueit",pt:"Onde é meu portão"},
{m:"airport",en:"Where is immigration?",pron:"uer iz imigreixon",pt:"Onde fica a imigração"},
{m:"airport",en:"Where is baggage claim?",pron:"uer iz baguej cleim",pt:"Onde retiro a bagagem"},
{m:"airport",en:"Where is security?",pron:"uer iz sicuriti",pt:"Onde é a segurança"},
{m:"airport",en:"Where is the restroom?",pron:"uer iz dhi restrum",pt:"Onde fica o banheiro"},
{m:"airport",en:"My flight is delayed",pron:"mai flait iz dileid",pt:"Meu voo está atrasado"},
{m:"airport",en:"My flight was canceled",pron:"mai flait was cênseld",pt:"Meu voo foi cancelado"},
{m:"airport",en:"I lost my luggage",pron:"ai lost mai laguedj",pt:"Perdi minha bagagem"},
{m:"airport",en:"Where is the boarding gate?",pron:"uer iz dhi boarding gueit",pt:"Onde fica o portão de embarque"},
{m:"airport",en:"Where can I check in?",pron:"uer ken ai tchekin",pt:"Onde faço check-in"},
{m:"airport",en:"Where is customs?",pron:"uer iz câstoms",pt:"Onde é a alfândega"},
{m:"airport",en:"I need help",pron:"ai nid help",pt:"Preciso de ajuda"},
{m:"airport",en:"My passport please",pron:"mai passport plis",pt:"Meu passaporte por favor"},
{m:"airport",en:"Where is the exit?",pron:"uer iz dhi exit",pt:"Onde é a saída"},
{m:"airport",en:"Which terminal?",pron:"uich terminal",pt:"Qual terminal"},
{m:"airport",en:"Where can I get a taxi?",pron:"uer ken ai get a taxi",pt:"Onde posso pegar um taxi"},
{m:"airport",en:"Is this the boarding line?",pron:"iz dis dhi boarding lain",pt:"Essa é a fila de embarque"},
{m:"airport",en:"How long is the delay?",pron:"rau long iz dhi dilei",pt:"Quanto tempo de atraso"},
{m:"airport",en:"Where is the information desk?",pron:"uer iz dhi informêixon desk",pt:"Onde fica o balcão de informação"},

// HOTEL
{m:"hotel",en:"I have a reservation",pron:"ai hev a reserveyshon",pt:"Eu tenho uma reserva"},
{m:"hotel",en:"What time is check in?",pron:"uat taim iz tchekin",pt:"Que horas é o check-in"},
{m:"hotel",en:"What time is checkout?",pron:"uat taim iz tchekaut",pt:"Que horas é o checkout"},
{m:"hotel",en:"Is breakfast included?",pron:"iz brekfast included",pt:"Café da manhã está incluído"},
{m:"hotel",en:"Where is the elevator?",pron:"uer iz dhi elevêitor",pt:"Onde fica o elevador"},
{m:"hotel",en:"Can I get another towel?",pron:"ken ai get anader tauel",pt:"Pode trazer outra toalha"},
{m:"hotel",en:"The air conditioner is not working",pron:"dhi er conditioner iz not uorking",pt:"O ar condicionado não funciona"},
{m:"hotel",en:"Can I change rooms?",pron:"ken ai tcheinj rums",pt:"Posso trocar de quarto"},
{m:"hotel",en:"Where is my room?",pron:"uer iz mai rum",pt:"Onde é meu quarto"},
{m:"hotel",en:"Do you have wifi?",pron:"du iu hev uaifai",pt:"Vocês tem wifi"},
{m:"hotel",en:"What is the wifi password?",pron:"uat iz dhi uaifai pasuord",pt:"Qual a senha do wifi"},
{m:"hotel",en:"Can I leave my luggage?",pron:"ken ai liv mai laguedj",pt:"Posso deixar minha bagagem"},
{m:"hotel",en:"I need a taxi",pron:"ai nid a taxi",pt:"Preciso de um taxi"},
{m:"hotel",en:"Where is the lobby?",pron:"uer iz dhi lobi",pt:"Onde é o lobby"},
{m:"hotel",en:"Where is the restaurant?",pron:"uer iz dhi restaurant",pt:"Onde é o restaurante"},
{m:"hotel",en:"Do you have room service?",pron:"du iu hev rum service",pt:"Tem serviço de quarto"},
{m:"hotel",en:"Can I get extra pillows?",pron:"ken ai get extra pilous",pt:"Pode trazer travesseiros extras"},
{m:"hotel",en:"Is the gym open?",pron:"iz dhi jim open",pt:"A academia está aberta"},
{m:"hotel",en:"Where is the pool?",pron:"uer iz dhi pul",pt:"Onde fica a piscina"},
{m:"hotel",en:"Can you call a taxi?",pron:"ken iu col a taxi",pt:"Pode chamar um taxi"},

// RESTAURANT
{m:"restaurant",en:"Can I see the menu?",pron:"ken ai si dhi menu",pt:"Posso ver o cardápio"},
{m:"restaurant",en:"What do you recommend?",pron:"uat du iu recomênd",pt:"O que você recomenda"},
{m:"restaurant",en:"Water please",pron:"uóter plis",pt:"Água por favor"},
{m:"restaurant",en:"No ice please",pron:"nou ais plis",pt:"Sem gelo por favor"},
{m:"restaurant",en:"This is delicious",pron:"dis iz dilíshas",pt:"Isso está delicioso"},
{m:"restaurant",en:"Can I get the check?",pron:"ken ai get dhi tchek",pt:"A conta por favor"},
{m:"restaurant",en:"I am vegetarian",pron:"ai am vegeterian",pt:"Sou vegetariano"},
{m:"restaurant",en:"Do you have beer?",pron:"du iu hev bir",pt:"Vocês tem cerveja"},
{m:"restaurant",en:"Do you have wine?",pron:"du iu hev uain",pt:"Vocês tem vinho"},
{m:"restaurant",en:"One coffee please",pron:"uan cófi plis",pt:"Um café por favor"},
{m:"restaurant",en:"I would like this",pron:"ai uód laik dis",pt:"Eu gostaria disso"},
{m:"restaurant",en:"Two beers please",pron:"tu biers plis",pt:"Duas cervejas por favor"},
{m:"restaurant",en:"Do you accept card?",pron:"du iu acépt card",pt:"Aceitam cartão"},
{m:"restaurant",en:"Is service included?",pron:"iz service included",pt:"O serviço está incluído"},
{m:"restaurant",en:"Can we sit here?",pron:"ken ui sit rir",pt:"Podemos sentar aqui"},
{m:"restaurant",en:"A table for two",pron:"a teibol for tu",pt:"Mesa para dois"},
{m:"restaurant",en:"Do you have dessert?",pron:"du iu hev dizert",pt:"Tem sobremesa"},
{m:"restaurant",en:"Another water please",pron:"anader uóter plis",pt:"Outra água por favor"},
{m:"restaurant",en:"Everything was great",pron:"everithing uas greit",pt:"Estava tudo ótimo"},
{m:"restaurant",en:"Thank you",pron:"thenkiu",pt:"Obrigado"}

];
