const phrases=[

// AIRPORT
{m:"airport",en:"Where is the airport?",pron:"uer iz dhi erport",pt:"Onde fica o aeroporto"},
{m:"airport",en:"Where is my gate?",pron:"uer iz mai gueit",pt:"Onde é meu portão"},
{m:"airport",en:"Where is baggage claim?",pron:"uer iz baguej cleim",pt:"Onde retiro minha bagagem"},
{m:"airport",en:"Where is immigration?",pron:"uer iz imigreixon",pt:"Onde fica a imigração"},
{m:"airport",en:"Where is customs?",pron:"uer iz câstoms",pt:"Onde é a alfândega"},
{m:"airport",en:"Where is the restroom?",pron:"uer iz dhi réstrum",pt:"Onde fica o banheiro"},
{m:"airport",en:"My flight is delayed",pron:"mai flait iz dilêid",pt:"Meu voo está atrasado"},
{m:"airport",en:"My flight was canceled",pron:"mai flait uós cênseld",pt:"Meu voo foi cancelado"},
{m:"airport",en:"I lost my luggage",pron:"ai lost mai lâguej",pt:"Perdi minha bagagem"},
{m:"airport",en:"I need help",pron:"ai nid rélp",pt:"Preciso de ajuda"},
{m:"airport",en:"Where can I get a taxi?",pron:"uer kén ai guét a taxi",pt:"Onde posso pegar um taxi"},
{m:"airport",en:"Where is the exit?",pron:"uer iz dhi éksit",pt:"Onde é a saída"},
{m:"airport",en:"Where is the information desk?",pron:"uer iz dhi informêixon desk",pt:"Onde fica o balcão de informação"},
{m:"airport",en:"Which terminal?",pron:"uích terminal",pt:"Qual terminal"},
{m:"airport",en:"Where can I check in?",pron:"uer kén ai tchek in",pt:"Onde faço check in"},
{m:"airport",en:"Where is boarding?",pron:"uer iz bórding",pt:"Onde é o embarque"},
{m:"airport",en:"How long is the delay?",pron:"rau long iz dhi dilêi",pt:"Quanto tempo de atraso"},
{m:"airport",en:"Where is security?",pron:"uer iz sicuriti",pt:"Onde é a segurança"},
{m:"airport",en:"Where is my seat?",pron:"uer iz mai sit",pt:"Onde é meu assento"},
{m:"airport",en:"Can I see your passport?",pron:"ken ai si iór pásport",pt:"Posso ver seu passaporte"},

// HOTEL
{m:"hotel",en:"I have a reservation",pron:"ai rév a reserveyshon",pt:"Eu tenho uma reserva"},
{m:"hotel",en:"What time is check in?",pron:"uat taim iz tchekin",pt:"Que horas é o check in"},
{m:"hotel",en:"What time is checkout?",pron:"uat taim iz tchekaut",pt:"Que horas é o checkout"},
{m:"hotel",en:"Where is my room?",pron:"uer iz mai rum",pt:"Onde é meu quarto"},
{m:"hotel",en:"Where is the elevator?",pron:"uer iz dhi elevêitor",pt:"Onde fica o elevador"},
{m:"hotel",en:"Is breakfast included?",pron:"iz brekfast included",pt:"Café da manhã está incluído"},
{m:"hotel",en:"Do you have wifi?",pron:"du iu rév uaifai",pt:"Vocês tem wifi"},
{m:"hotel",en:"What is the wifi password?",pron:"uat iz dhi uaifai pasuord",pt:"Qual a senha do wifi"},
{m:"hotel",en:"Can I get another towel?",pron:"ken ai get anader tauel",pt:"Pode trazer outra toalha"},
{m:"hotel",en:"Can I change rooms?",pron:"ken ai tcheinj rums",pt:"Posso trocar de quarto"},
{m:"hotel",en:"I need a taxi",pron:"ai nid a taxi",pt:"Preciso de um taxi"},
{m:"hotel",en:"Where is the lobby?",pron:"uer iz dhi lobi",pt:"Onde é o lobby"},
{m:"hotel",en:"Where is the restaurant?",pron:"uer iz dhi restaurant",pt:"Onde fica o restaurante"},
{m:"hotel",en:"Do you have room service?",pron:"du iu rév rum service",pt:"Tem serviço de quarto"},
{m:"hotel",en:"Can I get extra pillows?",pron:"ken ai get extra pilous",pt:"Pode trazer travesseiros extras"},
{m:"hotel",en:"Is the gym open?",pron:"iz dhi jim open",pt:"A academia está aberta"},
{m:"hotel",en:"Where is the pool?",pron:"uer iz dhi pul",pt:"Onde fica a piscina"},
{m:"hotel",en:"Can you call a taxi?",pron:"ken iu col a taxi",pt:"Pode chamar um taxi"},
{m:"hotel",en:"Can I leave my luggage?",pron:"ken ai liv mai lâguej",pt:"Posso deixar minha bagagem"},
{m:"hotel",en:"Thank you",pron:"thenk iu",pt:"Obrigado"},

// RESTAURANT
{m:"restaurant",en:"Can I see the menu?",pron:"ken ai si dhi menu",pt:"Posso ver o cardápio"},
{m:"restaurant",en:"What do you recommend?",pron:"uat du iu recomênd",pt:"O que você recomenda"},
{m:"restaurant",en:"Water please",pron:"uóter plis",pt:"Água por favor"},
{m:"restaurant",en:"No ice please",pron:"nou ais plis",pt:"Sem gelo por favor"},
{m:"restaurant",en:"This is delicious",pron:"dis iz dilíshas",pt:"Isso está delicioso"},
{m:"restaurant",en:"Can I get the check?",pron:"ken ai get dhi tchek",pt:"A conta por favor"},
{m:"restaurant",en:"I am vegetarian",pron:"ai am vegitarian",pt:"Sou vegetariano"},
{m:"restaurant",en:"Do you have beer?",pron:"du iu rév bir",pt:"Vocês tem cerveja"},
{m:"restaurant",en:"Do you have wine?",pron:"du iu rév uain",pt:"Vocês tem vinho"},
{m:"restaurant",en:"One coffee please",pron:"uan cófi plis",pt:"Um café por favor"},
{m:"restaurant",en:"I would like this",pron:"ai uod laik dis",pt:"Eu gostaria disso"},
{m:"restaurant",en:"Two beers please",pron:"tu biers plis",pt:"Duas cervejas por favor"},
{m:"restaurant",en:"Do you accept card?",pron:"du iu acépt card",pt:"Aceitam cartão"},
{m:"restaurant",en:"Is service included?",pron:"iz service included",pt:"O serviço está incluído"},
{m:"restaurant",en:"A table for two",pron:"a teibol for tu",pt:"Mesa para dois"},
{m:"restaurant",en:"Can we sit here?",pron:"ken ui sit rir",pt:"Podemos sentar aqui"},
{m:"restaurant",en:"Do you have dessert?",pron:"du iu rév dizert",pt:"Tem sobremesa"},
{m:"restaurant",en:"Another water please",pron:"anader uóter plis",pt:"Outra água por favor"},
{m:"restaurant",en:"Everything was great",pron:"everithing uas greit",pt:"Estava tudo ótimo"},
{m:"restaurant",en:"Thank you very much",pron:"thenk iu veri mach",pt:"Muito obrigado"},

// TRANSPORTATION
{m:"transport",en:"Where is the subway?",pron:"uer iz dhi sabuei",pt:"Onde fica o metrô"},
{m:"transport",en:"Where is the bus stop?",pron:"uer iz dhi bus stop",pt:"Onde é o ponto de ônibus"},
{m:"transport",en:"How much is the ticket?",pron:"rau mach iz dhi ticket",pt:"Quanto custa a passagem"},
{m:"transport",en:"Take me to the airport",pron:"teik mi tu dhi erport",pt:"Me leve ao aeroporto"},
{m:"transport",en:"Stop here please",pron:"stop rir plis",pt:"Pare aqui por favor"},
{m:"transport",en:"How long does it take?",pron:"rau long das it teik",pt:"Quanto tempo demora"},
{m:"transport",en:"Is it far?",pron:"iz it far",pt:"É longe"},
{m:"transport",en:"I need a taxi",pron:"ai nid a taxi",pt:"Preciso de um taxi"},
{m:"transport",en:"Does this bus go downtown?",pron:"daz dis bus go daun taun",pt:"Esse ônibus vai para o centro"},
{m:"transport",en:"Where can I buy tickets?",pron:"uer kén ai bai tickets",pt:"Onde compro tickets"},
{m:"transport",en:"Which line?",pron:"uích lain",pt:"Qual linha"},
{m:"transport",en:"Which platform?",pron:"uích platiform",pt:"Qual plataforma"},
{m:"transport",en:"Where is the train station?",pron:"uer iz dhi trein steixon",pt:"Onde fica a estação de trem"},
{m:"transport",en:"I missed the bus",pron:"ai mist dhi bus",pt:"Perdi o ônibus"},
{m:"transport",en:"Where can I rent a car?",pron:"uer kén ai rent a car",pt:"Onde posso alugar um carro"},
{m:"transport",en:"How much is the fare?",pron:"rau mach iz dhi fer",pt:"Qual o valor da corrida"},
{m:"transport",en:"Please slow down",pron:"plis slou daun",pt:"Por favor vá mais devagar"},
{m:"transport",en:"Turn left",pron:"tern left",pt:"Vire à esquerda"},
{m:"transport",en:"Turn right",pron:"tern rait",pt:"Vire à direita"},
{m:"transport",en:"Thank you driver",pron:"thenk iu draiver",pt:"Obrigado motorista"},

// SHOPPING
{m:"shopping",en:"How much is this?",pron:"rau mach iz dis",pt:"Quanto custa isso"},
{m:"shopping",en:"Do you accept credit card?",pron:"du iu acépt crédit card",pt:"Aceita cartão de crédito"},
{m:"shopping",en:"Do you have a bigger size?",pron:"du iu rév a biger saiz",pt:"Tem um tamanho maior"},
{m:"shopping",en:"Do you have a smaller size?",pron:"du iu rév a smoler saiz",pt:"Tem um tamanho menor"},
{m:"shopping",en:"Where is the cashier?",pron:"uer iz dhi cashiêr",pt:"Onde fica o caixa"},
{m:"shopping",en:"Can I try this on?",pron:"ken ai trai dis on",pt:"Posso experimentar"},
{m:"shopping",en:"It is too expensive",pron:"it iz tu expensiv",pt:"Está muito caro"},
{m:"shopping",en:"Do you have another color?",pron:"du iu rév anader color",pt:"Tem outra cor"},
{m:"shopping",en:"I will take this",pron:"ai uil teik dis",pt:"Vou levar isso"},
{m:"shopping",en:"Can I get a discount?",pron:"ken ai get a discount",pt:"Pode dar desconto"},
{m:"shopping",en:"Where is the fitting room?",pron:"uer iz dhi fitting rum",pt:"Onde fica o provador"},
{m:"shopping",en:"Is there a sale?",pron:"iz der a seil",pt:"Tem promoção"},
{m:"shopping",en:"Do you have this in black?",pron:"du iu rév dis in black",pt:"Tem isso em preto"},
{m:"shopping",en:"Do you have this in white?",pron:"du iu rév dis in uait",pt:"Tem isso em branco"},
{m:"shopping",en:"Where is the mall?",pron:"uer iz dhi mol",pt:"Onde fica o shopping"},
{m:"shopping",en:"Can I return this?",pron:"ken ai return dis",pt:"Posso devolver isso"},
{m:"shopping",en:"Where is the store?",pron:"uer iz dhi stor",pt:"Onde fica a loja"},
{m:"shopping",en:"I am just looking",pron:"ai am just looking",pt:"Estou só olhando"},
{m:"shopping",en:"Can I pay in cash?",pron:"ken ai pei in cash",pt:"Posso pagar em dinheiro"},
{m:"shopping",en:"Thank you very much",pron:"thenk iu veri mach",pt:"Muito obrigado"},

// TOURISM
{m:"tourism",en:"Where is the museum?",pron:"uer iz dhi muzeum",pt:"Onde fica o museu"},
{m:"tourism",en:"Where is the park?",pron:"uer iz dhi park",pt:"Onde fica o parque"},
{m:"tourism",en:"Where is downtown?",pron:"uer iz daun taun",pt:"Onde fica o centro"},
{m:"tourism",en:"Where can I take photos?",pron:"uer kén ai teik fôtos",pt:"Onde posso tirar fotos"},
{m:"tourism",en:"Is it safe here?",pron:"iz it seif rir",pt:"É seguro aqui"},
{m:"tourism",en:"Where is the beach?",pron:"uer iz dhi bitch",pt:"Onde fica a praia"},
{m:"tourism",en:"Where is the hotel?",pron:"uer iz dhi hotel",pt:"Onde fica o hotel"},
{m:"tourism",en:"How do I get there?",pron:"rau du ai get der",pt:"Como chego lá"},
{m:"tourism",en:"Is it far?",pron:"iz it far",pt:"É longe"},
{m:"tourism",en:"Is it close?",pron:"iz it clous",pt:"É perto"},
{m:"tourism",en:"Where is the ticket office?",pron:"uer iz dhi ticket office",pt:"Onde fica a bilheteria"},
{m:"tourism",en:"Where is the entrance?",pron:"uer iz dhi entrans",pt:"Onde é a entrada"},
{m:"tourism",en:"Where is the exit?",pron:"uer iz dhi éksit",pt:"Onde é a saída"},
{m:"tourism",en:"Can you take a photo?",pron:"ken iu teik a fôto",pt:"Pode tirar uma foto"},
{m:"tourism",en:"What time does it open?",pron:"uat taim daz it open",pt:"Que horas abre"},
{m:"tourism",en:"What time does it close?",pron:"uat taim daz it clous",pt:"Que horas fecha"},
{m:"tourism",en:"Is there a tour?",pron:"iz der a tur",pt:"Tem tour"},
{m:"tourism",en:"How much is the ticket?",pron:"rau mach iz dhi ticket",pt:"Quanto custa o ticket"},
{m:"tourism",en:"Where is the guide?",pron:"uer iz dhi gaid",pt:"Onde está o guia"},
{m:"tourism",en:"I love this place",pron:"ai lov dis pleis",pt:"Eu amo esse lugar"},

// CONVERSATION
{m:"conversation",en:"Hello",pron:"relou",pt:"Olá"},
{m:"conversation",en:"Hi",pron:"rai",pt:"Oi"},
{m:"conversation",en:"Good morning",pron:"gud mornin",pt:"Bom dia"},
{m:"conversation",en:"Good afternoon",pron:"gud afternun",pt:"Boa tarde"},
{m:"conversation",en:"Good evening",pron:"gud ivnin",pt:"Boa noite"},
{m:"conversation",en:"How are you?",pron:"rau ar iu",pt:"Como você está"},
{m:"conversation",en:"I am fine",pron:"ai am fain",pt:"Estou bem"},
{m:"conversation",en:"Nice to meet you",pron:"nais tu mit iu",pt:"Prazer em conhecer"},
{m:"conversation",en:"Where are you from?",pron:"uer ar iu from",pt:"De onde você é"},
{m:"conversation",en:"I am from Brazil",pron:"ai am from brazil",pt:"Sou do Brasil"},
{m:"conversation",en:"Do you speak Portuguese?",pron:"du iu spik português",pt:"Você fala português"},
{m:"conversation",en:"I do not understand",pron:"ai du not anderstend",pt:"Não entendo"},
{m:"conversation",en:"Please speak slowly",pron:"plis spik slouli",pt:"Por favor fale devagar"},
{m:"conversation",en:"Can you repeat?",pron:"ken iu ripit",pt:"Pode repetir"},
{m:"conversation",en:"What is your name?",pron:"uat iz iór neim",pt:"Qual seu nome"},
{m:"conversation",en:"My name is...",pron:"mai neim iz",pt:"Meu nome é"},
{m:"conversation",en:"Nice to meet you",pron:"nais tu mit iu",pt:"Prazer"},
{m:"conversation",en:"See you later",pron:"si iu leiter",pt:"Até mais"},
{m:"conversation",en:"Have a nice day",pron:"rév a nais dei",pt:"Tenha um bom dia"},
{m:"conversation",en:"Goodbye",pron:"gud bai",pt:"Tchau"},

// EMERGENCY
{m:"emergency",en:"I need help",pron:"ai nid rélp",pt:"Preciso de ajuda"},
{m:"emergency",en:"Call the police",pron:"col dhi polís",pt:"Chame a polícia"},
{m:"emergency",en:"Call an ambulance",pron:"col an ambulance",pt:"Chame uma ambulância"},
{m:"emergency",en:"Where is the hospital?",pron:"uer iz dhi hospital",pt:"Onde fica o hospital"},
{m:"emergency",en:"I am lost",pron:"ai am lost",pt:"Estou perdido"},
{m:"emergency",en:"I need a doctor",pron:"ai nid a doctor",pt:"Preciso de um médico"},
{m:"emergency",en:"I feel sick",pron:"ai fil sik",pt:"Estou passando mal"},
{m:"emergency",en:"I was robbed",pron:"ai uas robd",pt:"Fui roubado"},
{m:"emergency",en:"Help me please",pron:"réulp mi plis",pt:"Me ajude por favor"},
{m:"emergency",en:"Where is the police station?",pron:"uer iz dhi polís steixon",pt:"Onde fica a delegacia"}

];
